### PR TITLE
cplay: Add suport for AAC audio codec

### PR DESCRIPTION
**Pull request by TangleZ**
Add parse_aac_header API to parse AAC streams, support ADTS and
ADIF format.

Signed-off-by: Zhang Peng <peng.zhang_8@nxp.com>

### CODE REVIEW

**Review by perexg — APPROVED** [review]
Looks fine.

**Review by dbaluta — APPROVED** [review]

**Comment by perexg** [comment]
@vinodkoul : Could you click 'rebase + merge' next time to avoid the merge commits? The Link: line may be used for the source reference (but it requires more patch work).

**Comment by dbaluta** [comment]
@perexg can you please make this default option? Github allows you to select the default option for merging. Also, I think we can gray out the rest of the options.

**Comment by perexg** [comment]
@dbaluta Done. Thank you for your pointer. I missed that this option was added...

**Comment by vinodkoul** [comment]
Thanks @perexg I wont have to worry about it :-)

**Pull request merged**
